INSERT INTO carteata.user VALUES (1,'Cihan-Catarau','Svetlana','cihansvetlana@gmail.com','sveta.11');
commit;
INSERT INTO carteata.user VALUES (2,'Catarau','Vadim','vadikatarau@yahoo.com','vadim.12');
commit;
INSERT INTO carteata.user VALUES (3,'Botezatu','Ion','ionbotezatu@gmail.com','ionbotezatu');
commit;
INSERT INTO carteata.user VALUES (4,'Botezatu','Nadejda','nadeabotezatu@gmail.com','nadeabotezatu');
commit;
INSERT INTO carteata.user VALUES (5,'Botezatu','Marius','bmariusotezatu@gmail.com','mariusbotezatu1');
commit;
INSERT INTO carteata.user VALUES (6,'Cihan','Maria','cihanmaria@gmail.com','mariacihan18');
commit;
INSERT INTO carteata.user VALUES (7,'Fotescu','Ecaterina','ecaterinafotescu@gmail.com','fotescu1998');
commit;
INSERT INTO carteata.user VALUES (9,'Bodrug','Daniela','danielabodrug@gmail.com','daniela26');
commit;
INSERT INTO carteata.user VALUES (10,'Moscaliuc','Vasile','vasilemoscaliuc@gmail.com','stefania26');
commit;
INSERT INTO carteata.user VALUES (11,'Balan','Corina','balancorina@gmail.com','corina26');
commit;
INSERT INTO carteata.user VALUES (12,'Pintea','Catalina','catalinapintea@gmail.com','pintea25');
commit;
INSERT INTO carteata.user VALUES (13,'Zgureanu','Ionela','ionelazgureanu@gmail.com','zgureanu.22');
commit;
INSERT INTO carteata.user VALUES (14,'Cihan','Ecaterina','ecaterinacihan@gmail.com','ecaterina.79');
commit;
INSERT INTO carteata.user VALUES (15,'Cihan','Ana','anacihan@gmail.com','cihan.ana14');
commit;
INSERT INTO carteata.user VALUES (16,'Fotescu','Ana','fotescuana@gmail.com','ana.fotescu');
commit;
INSERT INTO carteata.user VALUES (17,'Bodrug','Elena','elenabodrug@gmail.com','elena.96');
commit;
INSERT INTO carteata.user VALUES (18,'Nica','Gheorghe','gheorghenica@gmail.com','george.nica.96');
commit;
INSERT INTO carteata.user VALUES (19,'Bors','Vasile','borsvasile@gmail.com','bors123');
commit;
INSERT INTO carteata.user VALUES (20,'Bulmaga','Mihail','bulmagamihail@gmail.com','maikal34');
commit;

INSERT INTO carteata.book VALUES (1,"Retete pentru pofticiosi.jpg","Retete pentru pofticiosi",2,"For You",2002,226,"Beletristica",562172, 212.50);
INSERT INTO carteata.book VALUES (2,"un om fericit.jpg","Un om fericit",1,"Art",2022,240,"Beletristica",704440, 178.60);
INSERT INTO carteata.book VALUES (3,"1001 de carti.jpg","1001 de carti",3,"RAO",2016,223,"Beletristica",521856, 500.00);
INSERT INTO carteata.book VALUES (4,"Ghidul unei familii durabile_.jpg","Ghidul unei familii durabile",4,"Curtea Veche",2022,272,"Beletristica",687000, 162.10);
INSERT INTO carteata.book VALUES (5,"Abecedarul egalitatii.jpg","Abecedarul egalitatii",5,"Bons Offices",2022,114,"Carti pentru copii",705750, 321.70);
INSERT INTO carteata.book VALUES (6,"abecedarul amuzant.jpg","Abecedarul amuzant",6,"Bons Offices",2022,127,"Carti pentru copii",704769, 149.20);
INSERT INTO carteata.book VALUES (7,"Hotul de carti.jpg","Hotul de carti",7,"RAO",2011,568,"Beletristica",381756, 180.90);
INSERT INTO carteata.book VALUES (8,"Omul in epoca inteligentei artificiale.jpg","Omul in epoca inteligentei artificiale",8,"Corint",2021,352,"Beletristica",682413, 214.60);
INSERT INTO carteata.book VALUES (9,"Portretul lui Dorian Gray.jpg","Portretul lui Dorian Gray",9,"Humanitas",2021,296,"Beletristica",665556, 356.70);
INSERT INTO carteata.book VALUES (10,"Totul incepe cu noi.jpg","Totul incepe cu noi",10,"Epica",2023,368,"Beletristica",708390, 166.70);
INSERT INTO carteata.book VALUES (11,"Cel mai bogat om din babilon.jpg","Cel mai bogat om din babilon",11,"Amaltea",2004,144,"Beletristica",195525, 259.50);
INSERT INTO carteata.book VALUES (12,"Creerul copilului tau.jpg","Creerul copilului tau",12,"For You",2009,162,"Beletristica",562173, 167.20);
INSERT INTO carteata.book VALUES (13,"fluturi.jpg","Fluturi",13,"For You",2013,681,"Beletristica",315280, 358.90);
INSERT INTO carteata.book VALUES (14,"ipoteza fericirii.jpg","Ipoteza fericirii",14,"Humanitas",2020,421,"Beletristica",689368, 180.30);
INSERT INTO carteata.book VALUES (15,"Lumea creata de inteligenta artificiala.jpg","Superputerile inteligentei artificiale",8,"Corint",2021,352,"Beletristica",682414, 269.40);
INSERT INTO carteata.book VALUES (16,"Rezerva.jpg","Rezerva",15,"Nemira",2023,456,"Beletristica",705702, 480.10);
INSERT INTO carteata.book VALUES (17,"Dictionar de ononime.jpg","Dictionar de ononime",16,"Stiinta",2007,556,"Dicionare",325108, 84.10);
INSERT INTO carteata.book VALUES (18,"Dictionar explicativ ilustrat.jpg","Dictionar explicativ ilustrat",16,"ARC",2010,2280,"Dicionare",306499, 615.80);
INSERT INTO carteata.book VALUES (19,"Dictionar explicativ scolar.jpg","Dictionar explicativ scolar",17,"Stiinta",2021,432,"Dicionare",314680, 69.00);
INSERT INTO carteata.book VALUES (20,"Dictionar Roman-Englez.jpg","Dictionar Roman-Englez",18,"Teora",2006,1336,"Dicionare",445426, 432.90);
INSERT INTO carteata.book VALUES (21,"limba romana cl12.jpg","Limba romana cl 12",19,"Cartier",2021,156,"Manuale scolare",674391, 49.00);
INSERT INTO carteata.book VALUES (22,"Matemateca cl12.jpg","Matemateca cl 12",20,"Tipografia Orhei",2021,169,"Manuale scolare",669595, 53.00);
INSERT INTO carteata.book VALUES (23,"Informarica cl12.jpg","Informatica cl 12",21,"Stiinta",2019,145,"Manuale scolare",627975, 42.00);
commit;

INSERT INTO carteata.author VALUES (1,'Jaky','Eddie',98,'Germania');
INSERT INTO carteata.author VALUES (2,'Turcan','Valeria',29,'Chisinau');
INSERT INTO carteata.author VALUES (3,'Boxall','Peter',83,'Marea Britanie');
INSERT INTO carteata.author VALUES (4,'Chapman','Gary',85,'SUA');
INSERT INTO carteata.author VALUES (5,'Adamciuc','Ludmila',28,'Republica Moldova');
INSERT INTO carteata.author VALUES (6,'Gacikevici','Grigore',42,'Republica Moldova');
INSERT INTO carteata.author VALUES (7,'Zusac','Markus',48,'Australia');
INSERT INTO carteata.author VALUES (8,'Kai-Fu','Lee',62,'China');
INSERT INTO carteata.author VALUES (9,'Wilde','Oscar',87,'Dublin');
INSERT INTO carteata.author VALUES (11,'Clason','Samuel Clason',82,'SUA');
INSERT INTO carteata.author VALUES (12,'Siegel','Dan',66,'SUA');
INSERT INTO carteata.author VALUES (13,'Binder','Irina',38,'Ramania');
INSERT INTO carteata.author VALUES (14,'Haidt','Jonathan',60,'SUA');
INSERT INTO carteata.author VALUES (15,'Printul','Harry',39,'Marea Britanie');
INSERT INTO carteata.author VALUES (16,'Bahnaru','Viorel',73,'Republica Moldova');
INSERT INTO carteata.author VALUES (17,'Hincu','Dumitru',48,'Republica Moldova');
INSERT INTO carteata.author VALUES (18,'Levitchi','Leon',79,'Republica Moldova');
INSERT INTO carteata.author VALUES (19,'Condrea','Igor',79,'Republica Moldova');
INSERT INTO carteata.author VALUES (20,'Iavorschi','Victor',63,'Republica Moldova');
INSERT INTO carteata.author VALUES (21,'Anghel','Traian',52,'Republica Moldova');
commit;


UPDATE carteata.book
SET EditionName = 'Bons Offices'
WHERE BookId = 5;


